//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niacomsoft....Private.CoreLib.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Niacomsoft.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid method parameter value. 的本地化字符串。
        /// </summary>
        internal static string ArgumentException_default_message {
            get {
                return ResourceManager.GetString("ArgumentException_default_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid method ({0}) parameter value. The parameter name is {1}. 的本地化字符串。
        /// </summary>
        internal static string ArgumentException_with_method_and_parameter_name {
            get {
                return ResourceManager.GetString("ArgumentException_with_method_and_parameter_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid method parameter value. The parameter name is {0}. 的本地化字符串。
        /// </summary>
        internal static string ArgumentException_with_parameter_name {
            get {
                return ResourceManager.GetString("ArgumentException_with_parameter_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This method may be missing a required parameter value. 的本地化字符串。
        /// </summary>
        internal static string ArgumentNullException_default_message {
            get {
                return ResourceManager.GetString("ArgumentNullException_default_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The method &quot;{0}&quot; may be missing the required parameter value: {1}. 的本地化字符串。
        /// </summary>
        internal static string ArgumentNullException_with_method_and_parameter_name {
            get {
                return ResourceManager.GetString("ArgumentNullException_with_method_and_parameter_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This method may be missing a required parameter value: {0}. 的本地化字符串。
        /// </summary>
        internal static string ArgumentNullException_with_parameter_name {
            get {
                return ResourceManager.GetString("ArgumentNullException_with_parameter_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} days ago 的本地化字符串。
        /// </summary>
        internal static string DateTime_GetDescription_days {
            get {
                return ResourceManager.GetString("DateTime_GetDescription_days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dd/MM/yyyy 的本地化字符串。
        /// </summary>
        internal static string DateTime_GetDescription_default {
            get {
                return ResourceManager.GetString("DateTime_GetDescription_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} hours ago 的本地化字符串。
        /// </summary>
        internal static string DateTime_GetDescription_hours {
            get {
                return ResourceManager.GetString("DateTime_GetDescription_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Just now 的本地化字符串。
        /// </summary>
        internal static string DateTime_GetDescription_just_now {
            get {
                return ResourceManager.GetString("DateTime_GetDescription_just_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} minutes ago 的本地化字符串。
        /// </summary>
        internal static string DateTime_GetDescription_minutes {
            get {
                return ResourceManager.GetString("DateTime_GetDescription_minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dd/MM 的本地化字符串。
        /// </summary>
        internal static string DateTime_GetDescription_same_year {
            get {
                return ResourceManager.GetString("DateTime_GetDescription_same_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The directory does not exist. 的本地化字符串。
        /// </summary>
        internal static string DirectoryNotFoundException_default_message {
            get {
                return ResourceManager.GetString("DirectoryNotFoundException_default_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The directory &quot;{0}&quot; does not exist. 的本地化字符串。
        /// </summary>
        internal static string DirectoryNotFoundException_with_dir_path {
            get {
                return ResourceManager.GetString("DirectoryNotFoundException_with_dir_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When &quot;{0}&quot;, an exception of type &quot;{1}&quot; is thrown: {2} 的本地化字符串。
        /// </summary>
        internal static string Exception_get_summary_with_reason {
            get {
                return ResourceManager.GetString("Exception_get_summary_with_reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When method &quot;{0}&quot; is called, an exception of type &quot;{1}&quot; is thrown: {2} 的本地化字符串。
        /// </summary>
        internal static string Exception_get_summary_without_reason {
            get {
                return ResourceManager.GetString("Exception_get_summary_without_reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The file does not exist. 的本地化字符串。
        /// </summary>
        internal static string FileNotFoundException_default_message {
            get {
                return ResourceManager.GetString("FileNotFoundException_default_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The file &quot;{0}&quot; does not exist. 的本地化字符串。
        /// </summary>
        internal static string FileNotFoundException_with_file_path {
            get {
                return ResourceManager.GetString("FileNotFoundException_with_file_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid network communication port number. 的本地化字符串。
        /// </summary>
        internal static string InvalidPortException_default_message {
            get {
                return ResourceManager.GetString("InvalidPortException_default_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid network communication port number &quot;{0}&quot;. 的本地化字符串。
        /// </summary>
        internal static string InvalidPortException_with_port {
            get {
                return ResourceManager.GetString("InvalidPortException_with_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debug 的本地化字符串。
        /// </summary>
        internal static string LogLevel_Debug {
            get {
                return ResourceManager.GetString("LogLevel_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string LogLevel_Error {
            get {
                return ResourceManager.GetString("LogLevel_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fatal 的本地化字符串。
        /// </summary>
        internal static string LogLevel_Fatal {
            get {
                return ResourceManager.GetString("LogLevel_Fatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Information 的本地化字符串。
        /// </summary>
        internal static string LogLevel_Information {
            get {
                return ResourceManager.GetString("LogLevel_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trace 的本地化字符串。
        /// </summary>
        internal static string LogLevel_Tace {
            get {
                return ResourceManager.GetString("LogLevel_Tace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        internal static string LogLevel_Warning {
            get {
                return ResourceManager.GetString("LogLevel_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid macro parameter name. You may have provided null or whitespace. 的本地化字符串。
        /// </summary>
        internal static string MacroParameterException_invalid_name_empty_name {
            get {
                return ResourceManager.GetString("MacroParameterException_invalid_name_empty_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid macro parameter name. You may have provided special characters other than letters, numbers, minus signs, and underscores. 的本地化字符串。
        /// </summary>
        internal static string MacroParameterException_invalid_name_not_match {
            get {
                return ResourceManager.GetString("MacroParameterException_invalid_name_not_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The resource name is required. It should not be null, &quot;String.Empty&quot;, or all whitespace. 的本地化字符串。
        /// </summary>
        internal static string ResourceStringResolver_not_support_resource_name {
            get {
                return ResourceManager.GetString("ResourceStringResolver_not_support_resource_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System.Resources.ResourceManager Object Instance is required. 的本地化字符串。
        /// </summary>
        internal static string ResourceStringResolver_not_support_resourcemanager {
            get {
                return ResourceManager.GetString("ResourceStringResolver_not_support_resourcemanager", resourceCulture);
            }
        }
    }
}
